- hosts: localhost  
  connection: local  
  tasks:  
    - name: Create & Start Container    
      docker_container:      
        name: myweb      
        image: "hyeonji511/jenkinsfiledocker:latest"      
        state: started      
        ports:      
          - "80:8080"
